"""add salary slip url to loans

Revision ID: 6ae20e361c33
Revises: 3878006f0863
Create Date: 2026-09-04 12:26:59.825506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ae20e361c33'
down_revision: Union[str, Sequence[str], None] = '3878006f0863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('salary_slip_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'salary_slip_url')
    # ### end Alembic commands ###
